# Generated by Django 4.2.2 on 2023-06-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('Senha', models.CharField(max_length=100)),
                ('nascimento', models.CharField(max_length=50)),
                ('nickLol', models.CharField(max_length=30)),
                ('nickValorant', models.CharField(max_length=30)),
                ('saldo', models.CharField(max_length=10000000)),
                ('pix', models.CharField(max_length=100)),
            ],
        ),
    ]
