# Generated by Django 4.2.2 on 2023-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cperfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('nickLol', models.CharField(max_length=30)),
                ('nickValorant', models.CharField(max_length=30)),
                ('saldo', models.CharField(max_length=1000000000)),
                ('pix', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='perfil',
        ),
    ]
